package app.taskvault.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0058be)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF2170e4)
val md_theme_light_onPrimaryContainer = Color(0xFFfefcff)
val md_theme_light_secondary = Color(0xFF006c49)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF6cf8bb)
val md_theme_light_onSecondaryContainer = Color(0xFF00714d)
val md_theme_light_tertiary = Color(0xFF825100)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFa36700)
val md_theme_light_onTertiaryContainer = Color(0xFFfffbff)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFf9f9ff)
val md_theme_light_onBackground = Color(0xFF141b2b)
val md_theme_light_surface = Color(0xFFf9f9ff)
val md_theme_light_onSurface = Color(0xFF141b2b)
val md_theme_light_surfaceVariant = Color(0xFFdce2f7)
val md_theme_light_onSurfaceVariant = Color(0xFF424754)
val md_theme_light_outline = Color(0xFF727785)
val md_theme_light_inverseOnSurface = Color(0xFFedf0ff)
val md_theme_light_inverseSurface = Color(0xFF293040)
val md_theme_light_inversePrimary = Color(0xFFadc6ff)

val md_theme_dark_primary = Color(0xFFadc6ff)
val md_theme_dark_onPrimary = Color(0xFF001a42)
val md_theme_dark_primaryContainer = Color(0xFF004395)
val md_theme_dark_onPrimaryContainer = Color(0xFFd8e2ff)
val md_theme_dark_secondary = Color(0xFF4edea3)
val md_theme_dark_onSecondary = Color(0xFF002113)
val md_theme_dark_secondaryContainer = Color(0xFF005236)
val md_theme_dark_onSecondaryContainer = Color(0xFF6ffbbe)
val md_theme_dark_tertiary = Color(0xFFffb95f)
val md_theme_dark_onTertiary = Color(0xFF2a1700)
val md_theme_dark_tertiaryContainer = Color(0xFF653e00)
val md_theme_dark_onTertiaryContainer = Color(0xFFffddb8)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF141b2b)
val md_theme_dark_onBackground = Color(0xFFe1e8fd)
val md_theme_dark_surface = Color(0xFF141b2b)
val md_theme_dark_onSurface = Color(0xFFe1e8fd)
val md_theme_dark_surfaceVariant = Color(0xFF424754)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c6d6)
val md_theme_dark_outline = Color(0xFF8c91a0)
val md_theme_dark_inverseOnSurface = Color(0xFF141b2b)
val md_theme_dark_inverseSurface = Color(0xFFe1e8fd)
val md_theme_dark_inversePrimary = Color(0xFF0058be)
